#!/usr/bin/env bash

commitMessage=${1?Error: No commit message given};
git add .
git branch -M feature-branch
git commit -m "$commitMessage"
git push origin feature-branch
gh pr create --title "$commitMessage" --body "$commitMessage"
gh pr merge feature-branch
git checkout main
git branch --delete feature-branch